name: rz-g2l-ebk
summary: Renesas RZ/G2L Evaluation Board
description: |
 Support files for booting RZ/G2L Evaluation Board

version: 24-1
type: gadget

base: core24

platforms:
  arm64:
    build-on: [amd64, arm64]
    build-for: arm64

confinement: strict
grade: stable

parts:
  arm-trusted-firmware:
    plugin: nil
    source: https://github.com/renesas-rz/rzg_trusted-firmware-a.git
    source-type: git
    source-tag: v2.9/rz
    source-depth: 1
    build-environment:
      - MACHINE: "smarc-rzg2l"
      - PLAT: "g2l"
      - BOARD: "smarc_2"
      - BOARD_PMIC: "smarc_pmic_2"
      - CROSS_COMPILE: "${CRAFT_ARCH_TRIPLET_BUILD_FOR}-"
      - CC: "${CRAFT_ARCH_TRIPLET_BUILD_FOR}-gcc"
    override-build: |
      make \
        PLAT=${PLAT} \
        BOARD=${BOARD} \
        BUILD_BASE=${CRAFT_PART_BUILD}/build \
        bl2 \
        bl31 \
        -j$(nproc)

      make clean
      make \
        PLAT=${PLAT} \
        BOARD=${BOARD_PMIC} \
        BUILD_BASE=${CRAFT_PART_BUILD}/build-pmic \
        bl2 \
        bl31 \
        -j$(nproc)

      install -D -m 0644 build/${PLAT}/release/bl2.bin ${CRAFT_PART_INSTALL}/blobs/bl2-${MACHINE}.bin
      install -D -m 0644 build/${PLAT}/release/bl31.bin ${CRAFT_PART_INSTALL}/blobs/bl31-${MACHINE}.bin
      install -D -m 0644 build-pmic/${PLAT}/release/bl2.bin ${CRAFT_PART_INSTALL}/blobs/bl2-${MACHINE}_pmic.bin
      install -D -m 0644 build-pmic/${PLAT}/release/bl31.bin ${CRAFT_PART_INSTALL}/blobs/bl31-${MACHINE}_pmic.bin
    prime:
      - -*

build-snaps:
  - yq

build-packages:
  - arm-trusted-firmware-tools
  - bison
  - build-essential
  - device-tree-compiler
  - flex
  - libxml2-dev
  - libssl-dev
  - pkgconf
  - python3
  - python3-cryptography
  - python3-pyelftools
  - python3-pycryptodome
  - wget
  - zlib1g-dev
  - on amd64:
    - gcc-aarch64-linux-gnu
    - uuid-dev:arm64
  - on arm64:
    - gcc
    - uuid-dev
