name: rz-g2l-ebk
summary: Renesas RZ/G2L Evaluation Board
description: |
 Support files for booting RZ/G2L Evaluation Board

version: 24-1
type: gadget

base: core24

platforms:
  arm64:
    build-on: [amd64, arm64]
    build-for: arm64

confinement: strict
grade: stable

build-snaps:
  - yq

build-packages:
  - arm-trusted-firmware-tools
  - bison
  - build-essential
  - device-tree-compiler
  - flex
  - libxml2-dev
  - libssl-dev
  - pkgconf
  - python3
  - python3-cryptography
  - python3-pyelftools
  - python3-pycryptodome
  - wget
  - zlib1g-dev
  - on amd64:
    - gcc-aarch64-linux-gnu
    - uuid-dev:arm64
  - on arm64:
    - gcc
    - uuid-dev
